### ISSUE TITLE
spec: overlays

### ISSUE THREAD

**Issue by rsteube** [rsteube/carapace-bin#1551]
### Request

Support overlay specs that are merged with existing (bridged) completion.
Often complex completions already exist, but the argument completion for a specific flag or positional is either missing or not giving the desired result.

### Proposed solution

Definition same as the spec files but in `~/.config/carapace/overlays/`.

### Anything else?

E.g. `doctl --output <TAB>`, which currently completes files instead of `[text|json]`:

```yaml
name: doctl
persistentflags:
  --output=: Desired output format [text|json]
completion:
  flag:
    output: [text, json]
```

Needs to be lenient and allow `unknown flags`.
