### ISSUE TITLE
bridge: actions should use vararg

### ISSUE THREAD

**Issue by rsteube** [rsteube/carapace-bin#1552]
### Request

Bridge actions should accept variable arguments so that specs can embed subcommands with predefined flags and arguments.

### Proposed solution

```go
func ActionArgcomplete(command ...string) carapace.Action {}
```

### Anything else?

Breaks current specs as these will need to pass an array:

```yaml
name: gitlog
completion:
  positionalany: ["$_bridge.CarapaceBin([git, log])"]
```
