### ISSUE TITLE
ActionFish: prevent loop

### ISSUE THREAD

**Issue by rsteube** [rsteube/carapace-bin#1610]
### Current Behavior

User spec bridging a fish command creates a loop when invoked in fish:

### Expected Behavior

Execute the fish completer.

### Steps To Reproduce

```yaml
name: animate
completion:
  positionalany: ["$_bridge.Fish([animate])"]
```

### Version

v0.23.0

### OS

- [X] Linux
- [ ] OSX
- [ ] Windows

### Shell

- [ ] Bash
- [ ] Elvish
- [X] Fish
- [ ] Nushell
- [ ] Oil
- [ ] Powershell
- [ ] Xonsh
- [ ] Zsh

### Anything else?

related #1602
