### ISSUE TITLE
env: placeholder completion

### ISSUE THREAD

**Issue by rsteube** [rsteube/carapace-bin#1862]
### Request

Environment variables can be [dynamic](https://developer.hashicorp.com/terraform/cli/config/environment-variables#tf_var_name).

### Proposed solution

Support placeholders in variable name defiinitions and completions to support this.
Might be good to use `variables`  or `env` as key instead of names.

```yaml
variables:
  STATIC: static name
  DYNAMIC_<dyn>:  dynamic name
completion:
  variable:
    STATIC: ["one", "two"] 
    DYNAMIC_<dyn>: ["three", "four"]
  placeholder:
    dyn: ["five", "six"]
```
